# https://woodruffw.github.io/zizmor/
rules:
  unpinned-uses:
    config:
      policies:
        # We trust GitHub not to have a security incident
        actions/*: ref-pin
        ncipollo/release-action: ref-pin
